### ISSUE TITLE
Using HUGO posts.

### ISSUE THREAD

**Issue by maacumba** [coolapso/hugo-theme-terminalcv#3]
Hi this is not so much an issue, but more a comment. 
I love the idea and how you executed.
Just got a bit down when i realized it is more about .js than Hugo.
Having said that I know it is up to me fork and modify. :)

Anyway, thank you for making it available.

**Comment by coolapso** [comment]
Hi, thank you! 

what is it that you want to modify or what is it that you need? I don't really understand what you mean. 

This Is a hugo template therefore any template will have the necessary code within the HTML / Javascript so that hugo can load it and generate the content based on what is specified on the config.yml

If there is any feature or anything that you would like feel free to suggest or make a PR and will be glad to take a look at it.

**Comment by maacumba** [comment]
Sorry, I'm also learning how to use Hugo.
But I though about how we make posts with other templates.
For exemple: the projects page. I would like to keep adding projects to the page.
Maybe also images. or imagine a blog within your template.
I'm trying thou.... like I said I'm not very experienced with hugo. 
But your theme, just as it is, as an interactive CV, it is great.
thank you

**Comment by coolapso** [comment]
That's the thing ... this template was not build with being a blog in mind therefore it lacks all the "blog" features. 

The intent here is to be a static page with the content generated by HUGO. 

you can easily add as much  projects on your config.yml 

```
projects:
    - title: Project Red
      color: red
      date: since 2019
      link: https://example.com
      description: Describing red stuff

    - title: Project Blue
      color: blue
      date: since 2016
      link: https://example.com/blue
      #description: nothing to describe

    - title: Project Default
      date: Since 2017
      link: https://example.com/default
      #description: not there either
``` 
      
then you generate the webssite .. the projects section will have all of those you added. 
Take a look at the the https://github.com/4s3ti/terminalcv/blob/master/exampleSite/config.yml 

might give you some hints.
